feat(player): 绑定滚轮下滑为播放下一句, close #127
ba-archive/blue-archive pull request #182
Opened 2023-10-06 03:52 UTC by ChangeSuger

issue #127

2023-10-06 06:11 UTC, Mark9804 requested changes
麻烦做一下节流或者防抖， `WheelEvent` 在启用了无限滚动的鼠标上会频繁触发

2023-10-06 07:23 UTC, Mark9804 approved these changes

2023-10-06 07:23 UTC, merged

2023-10-06 07:24 UTC, Mark9804 commented
感谢！

2023-10-07 06:17 UTC, Mark9804 commented
请问有 B 站 ID 吗，这边到时候加个致谢

2023-10-07 14:49 UTC, ChangeSuger commented
> 请问有 B 站 ID 吗，这边到时候加个致谢

B 站 UID: 35116470，❤